version: '3.5'

services:
  db_calc:
    container_name: db_calc
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=1q2w3er4
      - POSTGRES_USER=remus
    image: postgres:14.3-alpine
